### PR TITLE
Improve firewall rule consumption

### PR DESCRIPTION
**Pull request by drywheat**
/cc @lmickh

### CODE REVIEW

**Comment by drywheat** [comment]
I'm working on testing failure cases with attribute-based rules right now.

**Comment by lmickh** [comment]
Will need a update to os-base as well. We can use am1-test-0 for that.  It can be rebuilt if need be and is outside of the current restrictions of os-base in the production env.  

Extending the firewall_rule LWRP kind of ties us to the use of the 'firewall' cookbook, but I can't really think of a cleaner way to do it.  If we were to try to move away from 'firewall' in the future, it would make sense to just move to a different wrapper cookbook.

Looks like it should work assuming testing is fine.  We should probably test with the firewall_rule LWRP used in another recipe to make sure it doesn't conflict with the other cookbooks.   That way we can update and test the attribute driven rules one at a time.

**Comment by drywheat** [comment]
@lmickh Does it make sense to swallow and log firewall rule exceptions? Perhaps like so.

```ruby
  begin
    firewall_rule name do
      populate_optional_attrs(rule,
        :description, :position, :stateful, :direction, :source, :source_port,
        :destination, :dest_port, :interface, :dest_interface, :redirect_port,
        :logging, :protocol, :command, :port)
    end
  rescue => error
    Chef::Log.fatal 'There was an error processing a firewall rule!'
    Chef::Log.fatal error
  end
```

I believe that instead we don't want to compile & converge whenever a rule fails. That might leave our server in an indeterminate and non-functional state.

**Comment by drywheat** [comment]
I'm running tests to see what happens whenever an errant rule busts the run. So far it does not result in the removal of existing rules, which is the desired behavior.

**Comment by drywheat** [comment]
I reviewed the code in the **os-datadog** cookbook and the underlying community cookbook, and I'm not sure at this point how I can leverage them to push a notification to datadog.

If datadog is running on all production servers, then we should be alerted whenever a Chef run fails.  In this case, whenever a firewall rule fails, correct? Does that mean we just need to remove the `begin/rescue` block?

**Comment by lmickh** [comment]
You would want to look [here](https://github.com/DataDog/chef-handler-datadog/tree/master/lib/chef/handler) for the code I was talking about.  The os-datadog cookbook installs that handler to report events up.  Pretty sure you should be able to use it as well.  Another option is to to create an event through the api/v1/event endpoint ([docs here](http://docs.datadoghq.com/api/)).  The api key is in the datadog attribute.  Just do a node.recipe? first to make sure it is running on the machine.

If you want to alert on a firewall rule failure AND not bomb out on the Chef run, we need to go the datadog event/handler route.  If we are fine with the whole run bombing, we can just let the datadog handler report the failed chef run.  

I'm fine with going the second route, removing the ```begin/rescue```, whole run halts, and letting the handler report it.  Will keep it simpler for now.  We won't lose the previous firewall state (at least the portions in the attr files) and we can still get notified something failed.  Lets try that and see how it goes.  Can add in the exception handling later if we decide it is still needed.

**Comment by drywheat** [comment]
I just reviewed the code for the handler (leverages the underlying metrics, events and tags classes) and it doesn't look like the methods contained therein are designed for external use. Instead, I think we would have to use the [datadog client](https://github.com/DataDog/dogapi-rb) if we want to publish events.

I'll remove the `begin/rescue` for now and let the handler report failures.

**Pull request merged**
